### PR TITLE
Fix CI - update libusb version

### PR DESCRIPTION
**Pull request by noslaver**
Not sure if old package (`libusb-1.0`) was pulled, but this version (`libusb-1.0-0`) seems to download fine on my setup.

### CODE REVIEW

**Comment by Tiwalun** [comment]
Thanks for working on this!

I think we need the `-dev` version of the package, so `libusb-1.0-0-dev`. Could you please change it to that?

**Comment by noslaver** [comment]
> Thanks for working on this!
> 
> I think we need the `-dev` version of the package, so `libusb-1.0-0-dev`. Could you please change it to that?

No problem. I was able to install the original package using apt-get instead of apt.
Do you have any preference for the chosen solution?

**Comment by Tiwalun** [comment]
In the other repositories we use `apt` together with the `libusb-1.0-0-dev` package, I would prefer that here as well to keep it consistent. (See https://github.com/probe-rs/probe-rs/blob/8159a2c938a737ddad278a0df62f472384aee5e6/.github/workflows/ci.yml#L35)

Best would be some kind of shared workflow step, but as far as I know Github Actions doesn't support it, so we have to do it manually for each repository. 🙄

**Comment by noslaver** [comment]
Moved back to `apt` and installed `libusb-1.0-0-dev`.

**Review by Tiwalun — APPROVED** [review]
Thanks!

**Pull request merged**
